### PR TITLE
Ps/footer, plus new colors for header and sidebar

### PR DESCRIPTION
**Pull request by paulsancer**
Take a look into the color of the header and footer, also I changed results structure and styles for mobile to work, what do you think? @BernabeFelix @Bernabe-Felix 

image

### CODE REVIEW

**Comment by paulsancer** [comment]
For reference to the desktop view

image

**Comment by BernabeFelix** [comment]
I'm not sure about the orange but let's see what Guillermo says. Looks good tho

**Comment by paulsancer** [comment]
@Bernabe-Felix @BernabeFelix As long as my laptop (old one) is up and running you can see the last version of this PR with hot reload [here](http://148.243.206.211:8080).

**Comment by paulsancer** [comment]
@Bernabe-Felix @BernabeFelix  please take a look at it (including sidebar...), I would like to close this xD
[http://polkien-sancer.ddns.net:8080/](http://polkien-sancer.ddns.net:8080/)

**Comment by BernabeFelix** [comment]
Looks Gooood

**Review by BernabeFelix — APPROVED** [review]

**Pull request merged**
